version: '3.8'

networks:
  traefik-net:
    external: true

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8082"
      - "--log.level=DEBUG"
      - "--api.dashboard=true"       # This enables the dashboard
      - "--api.debug=true"  
      - "--accesslog=true"  
    ports:
      - "8082:8082"
      - "9080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - traefik-net

  dummy-server:
    image: nginx:alpine
    configs:
      - source: nginx_config
      - source: index_html
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dummy.rule=Host(`dummy.wsh-it.dk`)"
        - "traefik.http.routers.dummy.entrypoints=web"
        - "traefik.http.services.dummy.loadbalancer.server.port=8081"
        - "traefik.docker.network=traefik-net"
    environment:
      - SERVER_NAME=dummy.wsh-it.dk
    networks:
      - traefik-net
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

configs:
  nginx_config:
    file: ./nginx.conf
  index_html:
    file: ./index.html