version: '3.8'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_ADMIN_PORT:-8080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      placement:
        constraints:
          - node.role == manager
    configs:
      - source: env_file
        target: /app/.env

  dummy-server:
    image: nginx:alpine
    configs:
      - source: nginx_config
      - source: index_html
      - source: env_file
        target: /app/.env
    deploy:
      replicas: ${DUMMY_REPLICAS:-2}
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dummy.rule=Host(`${DUMMY_DOMAIN:-dummy.wsh-it.dk}`)"
        - "traefik.http.services.dummy.loadbalancer.server.port=80"
    environment:
      - SERVER_NAME=${DUMMY_DOMAIN:-dummy.wsh-it.dk}

configs:
  nginx_config:
    file: ./nginx.conf
  index_html:
    file: ./index.html
  env_file:
    file: ./.env