services:
  k8s-worker-node:
    image: registry.k8s.io/pause:latest
    env_file:
      - ../.env
    entrypoint: ["/bin/sh", "-c", "$K8S_JOIN_COMMAND"]
    privileged: true
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker-alt:/var/lib/docker
      - /var/lib/kubelet:/var/lib/kubelet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
