version: '3.8'

services:
  k8s-worker-node:
    image: k8s-worker-node:latest
    build:
      context: .
      dockerfile: workernode.Dockerfile
    env_file:
      - ../.env
    privileged: true
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker:/var/lib/docker
      - /var/lib/kubelet:/var/lib/kubelet
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    entrypoint: /usr/local/bin/join_worker.sh

